### PR TITLE
Print all data for `CollateralProvider` and `RefundProvider`

### PR DESCRIPTION
**Pull request by ArdenHide**

### CODE REVIEW

**Comment by ArdenHide** [comment]
We have one problem. We can't save the GIF image in DynamoDB because the GIF is too long.

image

GIF length - 1_472_700
JPG length - 100_484

**Comment by Lomet** [comment]
> We have one problem. We can't save the GIF image in DynamoDB because the GIF is too long.
> 
> image
> 
> GIF length - 1_472_700 PNG length - 100_484

save each image, combine them on request

**Comment by ArdenHide** [comment]
Let's try to use `apng` instead of `gif`

**Comment by ArdenHide** [comment]
Look like some code work don't correctly. It's saved data for RefundProvider(poolId = 6). Here we can see 4 saved images, but RefundProvider use one only 2 images

image

**Comment by ArdenHide** [comment]
Right now on, we try to receive Collateral image we receive timeout lambda exception (30 sec)

**Comment by ArdenHide** [comment]
> Right now on, we try to receive Collateral image we receive timeout lambda exception (30 sec)

Fixed, but now don't work GIF animation

**Review by Lomet — APPROVED** [review]
LGFM

**Pull request merged**
